name: 'Build APK'
inputs:
  working-dir:  # id of input
    description: 'Working directory'
    default: ./
runs:
  using: "composite"
  steps:
    - run: flutter pub get
      shell: bash
      working-directory: ${{ inputs.project-dir }}
    - run: flutter build apk
      shell: bash
      working-directory: ${{ inputs.project-dir }}
