name: Main

on:
  workflow_dispatch:
  push:
    tags:        
      - '*'

defaults:
  run:
    shell: bash
    working-directory: ./example/vitame

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          architecture: x64
          flutter-version: 3.7.12
      - run: flutter pub get
      - run: flutter build apk
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            readme.md
            upload.js
