name: Main

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

defaults:
  run:
    shell: bash
    working-directory: ./example/vitame

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Common
        uses: ./.github/actions/setup-common
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          project-dir: example/vitame
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            readme.md
            example/vitame/build/app/outputs/flutter-apk/app-release.apk
